import type { Metadata } from "next";

//'font opmization' do Next
//importando fonte e usando subset Latin e pré definindo peso
import { Rubik } from "next/font/google";
import '../public/style/global.css'

const rubik = Rubik({ subsets: ["latin"], 
weight: ['500', '700']});

//SEO
//os mecanismos de pesquisa usam os metadata para entender o contexto das páginas web 
//ao fornecer metadatas relevantes, as chances de sua página ser indexada e rankeada corretamente aumentam 
//isso pode aumentar a visibilidade e tráfego de seu site

export const metadata: Metadata = {

  //define o titulo da pagina, o que aparecerá na barra de navegação e em mecanismos de pesquisa 
  //ajuda os usuários e melhora o SEO da pág
  title: "Create Next App",

    //fornece uma breve descrição do conteúdo da página que normalmente aparece abaixo do título nas pesquisas
  description: "Generated by create next app",
};


//Define o componente RootLayout como export padrão
//recebe os filhos como 'props' que representa o que será englobado nesse layout

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
//é o que fornece estilo e metadata consistente através das múltiplas páginas do seu app next